import type { Job } from "./types";

export const INITIAL_JOBS: Job[] = [
  {
    id: "seed-1",
    companyName: "Willow & Oak",
    status: "Applied",
    dateApplied: "2026-07-03",
    dateLastContacted: "2026-07-09",
    messageStyle: "Friendly",
    contacts: [
      {
        id: "seed-1-c1",
        name: "Dana Reyes",
        role: "Recruiter",
        email: "dana@willowoak.co",
        linkedin: "linkedin.com/in/danareyes",
      },
    ],
    companyUrl: "https://willowoak.co",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes:
      "Reached out to Dana after the info session.\nWaiting to hear about a phone screen — follow up if nothing by Friday.",
    recruiterMessage: "",
    followupMessage: "",
  },
  {
    id: "seed-2",
    companyName: "Maple Grove Studio",
    status: "Interviewing",
    dateApplied: "2026-06-28",
    dateLastContacted: "2026-07-11",
    messageStyle: "Enthusiastic",
    contacts: [
      {
        id: "seed-2-c1",
        name: "Sam Ito",
        role: "Hiring Manager",
        email: "sam@maplegrove.design",
        linkedin: "",
      },
      {
        id: "seed-2-c2",
        name: "Priya N.",
        role: "Referral",
        email: "",
        linkedin: "linkedin.com/in/priyan",
      },
    ],
    companyUrl: "https://maplegrove.design",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes: "Second round scheduled for next Tuesday. Prep portfolio walk-through.",
    recruiterMessage: "",
    followupMessage: "",
  },
  {
    id: "seed-3",
    companyName: "Fern & Field",
    status: "Interested",
    dateApplied: "",
    dateLastContacted: "",
    messageStyle: "Formal",
    contacts: [],
    companyUrl: "https://fernandfield.io",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes: "Saw the opening on their careers page. Draft an intro note.",
    recruiterMessage: "",
    followupMessage: "",
  },
];
