import type { Job } from "./types";

export const INITIAL_JOBS: Job[] = [
  {
    id: "seed-1",
    companyName: "Willow & Oak",
    status: "Applied",
    dateApplied: "2026-07-03",
    dateLastContacted: "2026-07-09",
    messageStyle: "Friendly",
    contactName: "Dana Reyes",
    contactEmail: "dana@willowoak.co",
    contactLinkedIn: "linkedin.com/in/danareyes",
    companyUrl: "https://willowoak.co",
    referralName: "",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes:
      "Reached out to Dana after the info session.\nWaiting to hear about a phone screen — follow up if nothing by Friday.",
    recruiterMessage: "",
    followupMessage: "",
  },
  {
    id: "seed-2",
    companyName: "Maple Grove Studio",
    status: "Interviewing",
    dateApplied: "2026-06-28",
    dateLastContacted: "2026-07-11",
    messageStyle: "Enthusiastic",
    contactName: "Sam Ito",
    contactEmail: "sam@maplegrove.design",
    contactLinkedIn: "",
    companyUrl: "https://maplegrove.design",
    referralName: "Priya N.",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes: "Second round scheduled for next Tuesday. Prep portfolio walk-through.",
    recruiterMessage: "",
    followupMessage: "",
  },
  {
    id: "seed-3",
    companyName: "Fern & Field",
    status: "Interested",
    dateApplied: "",
    dateLastContacted: "",
    messageStyle: "Formal",
    contactName: "",
    contactEmail: "",
    contactLinkedIn: "",
    companyUrl: "https://fernandfield.io",
    referralName: "",
    jobPostingUrl: "",
    companyLinkedInUrl: "",
    extraLinks: "",
    notes: "Saw the opening on their careers page. Draft an intro note.",
    recruiterMessage: "",
    followupMessage: "",
  },
];
